version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - "> 6.8.0"
  - dependency-name: socket.io-client
    versions:
    - 4.0.1
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
- package-ecosystem: npm
  directory: "/server"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - jonfairbanks
  versioning-strategy: increase
  ignore:
  - dependency-name: eslint
    versions:
    - "> 6.8.0"
  - dependency-name: socket.io
    versions:
    - 4.0.1
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.16
    - 7.13.17
  - dependency-name: redis
    versions:
    - 3.1.1
    - 3.1.2
  - dependency-name: eslint-plugin-jsx-a11y
    versions:
    - 6.4.1
  - dependency-name: mongoose
    versions:
    - 5.12.4
