version: "2"
services:
    client:
        container_name: yo-client
        restart: always
        build: ./client
        ports:
        - "3000:3000"
        links:
            - api
    api:
        container_name: yo-api
        restart: always
        build: ./server
        ports:
            - "7000:7000"
        links:
            - mongo
    redis:
        container_name: yo-redis
        restart: always
        image: redis
        volumes:
            - ./cache:/data
        ports:
            - "6379:6379"
        links:
            - api
    mongo:
        container_name: yo-mongo
        restart: always
        image: mongo
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"