version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/client"
    update_schedule: "live"
    target_branch: "develop"
    default_assignees:
      - "jonfairbanks"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    version_requirement_updates: "increase_versions"
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "live"
    target_branch: "develop"
    default_assignees:
      - "jonfairbanks"
    automerged_updates:
      - match:
          dependency_type: "production"
          update_type: "semver:patch"
    version_requirement_updates: "increase_versions"