version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/client"
    update_schedule: "live"
    target_branch: "develop"
    default_assignees:
      - "jonfairbanks"
    allowed_updates:
        - match:
            update_type: "security"
  - package_manager: "javascript"
    directory: "/server"
    update_schedule: "live"
    target_branch: "develop"
    default_assignees:
      - "jonfairbanks"
    allowed_updates:
        - match:
            update_type: "security"